version: '3.0'
services:
  db:
    image: "mysql:5.7"
    environment:
      - MYSQL_DATABASE=research_hub
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  api:
    build: ../research-hub-api/
    depends_on:
      - "db"
  web:
    build: ../research-hub-web/
    depends_on:
      - "api"
  proxy:
    build: ../research-hub-proxy/
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
    volumes:
      - ./server-ca.crt:/server-ca.crt
      - ./server.crt:/server.crt
      - ./server.key:/server.key
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
    command: /bin/bash -c "/run-nginx.sh"
