version: '3.0'
services:
  db:
    build: ../mysql-auto-backup/
    environment:
      - MYSQL_DATABASE=research_hub
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./data/dump:/data
      - ./data/mysql:/var/lib/mysql
      - ./data/log/cron:/var/log/cron
      - ./data/log/mysql:/var/log/mysql
  api:
    build: ../research-hub-api/
    depends_on:
      - "db"
  web:
    build: ../research-hub-web/
  proxy:
    build: ../research-hub-proxy/
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
    volumes:
      - ./server-ca.crt:/server-ca.crt
      - ./server.crt:/server.crt
      - ./server.key:/server.key
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
    command: /bin/bash -c "/run-nginx.sh"
    depends_on:
      - "web"
      - "api"
