version: '3.0'
services:
  api:
    image: "alpine"
    restart: always
  web:
    image: "uoacer/research-hub-web:${TAG}"
    restart: always
  proxy:
    image: "uoacer/research-hub-proxy:${TAG}"
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
    volumes:
      - ./server-ca.crt:/server-ca.crt
      - ./server.crt:/server.crt
      - ./server.key:/server.key
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
    command: /bin/bash -c "/run-nginx.sh"
    depends_on:
      - "web"
      - "api"
    restart: always

