version: '3.0'
services:
  db:
    build: 
      context: ../mysql-auto-backup/
      args:
        - http_proxy
        - https_proxy
    environment:
      - DB_MYSQL_USER=${DB_MYSQL_USER}
      - DB_MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
      - DB_MYSQL_DATABASE=${DB_MYSQL_DATABASE}
      - MYSQL_DATABASE=${DB_MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_MYSQL_PASSWORD}
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./seed_db.py:/docker-entrypoint-initdb.d/seed_db.py
      - ./database.xlsx:/docker-entrypoint-initdb.d/database.xlsx
      - ./seed-db.sh:/docker-entrypoint-initdb.d/seed-db.sh
      - ./whitelist.sql:/docker-entrypoint-initdb.d/whitelist.sql
      - ${DB_DATA_DIR}/dump:/data
      - ${DB_DATA_DIR}/mysql:/var/lib/mysql
      - ${DB_DATA_DIR}/log/cron:/var/log/cron
      - ${DB_DATA_DIR}/log/mysql:/var/log/mysql
    restart: always
    ports:
      - 3306:3306
  api:
    build: 
      context: ../research-hub-api/
      args:
        - http_proxy
        - https_proxy
    environment:
      - DB_MYSQL_DATABASE=${DB_MYSQL_DATABASE}
      - DB_MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
      - DB_MYSQL_USER=${DB_MYSQL_USER}
      - SN_BASE_URL=${SN_BASE_URL}
      - SN_USER=${SN_USER}
      - SN_PASSWORD=${SN_PASSWORD}
      - CER_VM_ASSIGNMENT_GROUP_ID=${CER_VM_ASSIGNMENT_GROUP_ID}
      - CER_VM_BUSINESS_SERVICE_ID=${CER_VM_BUSINESS_SERVICE_ID}
      - CER_VM_WATCH_LIST=${CER_VM_WATCH_LIST}
    volumes:
      - ./application.properties:/application.properties
      - ${API_ASSETS_DIR}:/assets
    depends_on:
      - "db"
    restart: always
