version: '3.2'
services:
  db-staging:
    image: "mysql:5.7"
    environment:
      - MYSQL_DATABASE=research_hub
      - MYSQL_ROOT_PASSWORD
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  api-staging:
    image: "uoacer/research-hub-api:staging"
    volumes:
      - ./staging.properties:/application.properties
    depends_on:
      - "db-staging"
  web-staging:
    image: "nginx"
  proxy-staging:
    image: "uoacer/research-hub-proxy:staging"
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./server-ca.crt:/server-ca.crt
      - ./server.crt:/server.crt
      - ./server.key:/server.key
    environment:
      - SERVER_NAME=research-hub.cer.auckland.ac.nz
      - HTTP_PORT=8080
      - HTTPS_PORT=8443
      - WEB_NAME=web-staging
      - API_NAME=api-staging
    command: /bin/bash -c "/run-nginx.sh"