version: '3.0'
services:
  db:
    image: "uoacer/research-hub-db:${TAG}"
    environment:
      - MYSQL_DATABASE=research_hub
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - /data/${TAG}/dump:/data
      - /data/${TAG}/mysql:/var/lib/mysql
      - /data/${TAG}/log/cron:/var/log/cron
      - /data/${TAG}/log/mysql:/var/log/mysql
    restart: always
  api:
    image: "uoacer/research-hub-api:${TAG}"
    depends_on:
      - "db"
    restart: always
  web:
    image: "uoacer/research-hub-web:${TAG}"
    restart: always
  proxy:
    image: "uoacer/research-hub-proxy:${TAG}"
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
    volumes:
      - ./server-ca.crt:/server-ca.crt
      - ./server.crt:/server.crt
      - ./server.key:/server.key
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
    command: /bin/bash -c "/run-nginx.sh"
    depends_on:
      - "web"
      - "api"
    restart: always

