version: '3.0'
services:
  web:
    build:
      context: ../research-hub-web/
      args:
        - WEB_ENVIRONMENT=${WEB_ENVIRONMENT}
        - http_proxy
        - https_proxy
    restart: always
  proxy:
    build: 
       context: ../research-hub-proxy/
       args:
           - http_proxy
           - https_proxy
    ports:
      - "${PROXY_HTTP_PORT}:80"
      - "${PROXY_HTTPS_PORT}:443"
    volumes:
      - ./server-ca.crt:/usr/local/apache2/conf/keys/server-ca.crt
      - ./server.crt:/usr/local/apache2/conf/keys/server.crt
      - ./server.key:/usr/local/apache2/conf/keys/server.key
    environment:
      - PROXY_SERVER_NAME=${PROXY_SERVER_NAME}
      - PROXY_HTTP_PORT=${PROXY_HTTP_PORT}
      - PROXY_HTTPS_PORT=${PROXY_HTTPS_PORT}
    depends_on:
      - "web"
      - "api"
    restart: always
