version: '3'
services:
  web-staging:
    image: "nginx"
  api-staging:
    image: "httpd"
  proxy-staging:
    image: "uoacer/research-hub-proxy:staging"
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./server-ca.crt:/server-ca.crt
      - ./server.crt:/server.crt
      - ./server.key:/server.key
    environment:
      - SERVER_NAME=localhost
      - HTTP_PORT=8080
      - HTTPS_PORT=8443
      - WEB_NAME=web-staging
      - API_NAME=api-staging
    command: /bin/bash -c "/run-nginx.sh"