version: '3.0'
services:
  db:
    build:
      context: ../mysql-auto-backup/
      args:
        - http_proxy
        - https_proxy
    environment:
      - DB_MYSQL_USER=${DB_MYSQL_USER}
      - DB_MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
      - DB_MYSQL_DATABASE=${DB_MYSQL_DATABASE}
      - MYSQL_DATABASE=${DB_MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_MYSQL_PASSWORD}
    volumes:
      - ../research-hub-api/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./scripts/seed_db.py:/docker-entrypoint-initdb.d/seed_db.py
      - ${DATA_DIR}/config/database.xlsx:/docker-entrypoint-initdb.d/database.xlsx
      - ./scripts/seed-db.sh:/docker-entrypoint-initdb.d/seed-db.sh
      - ${DATA_DIR}/db/dump:/data
      - ${DATA_DIR}/db/mysql:/var/lib/mysql
      - ${DATA_DIR}/db/log/cron:/var/log/cron
      - ${DATA_DIR}/db/log/mysql:/var/log/mysql
    restart: always